-- MySQL Script generated by MySQL Workbench
-- Tue May 17 14:31:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ecommerce` ;

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ecommerce` DEFAULT CHARACTER SET utf8mb4 ;
USE `Ecommerce` ;

-- -----------------------------------------------------
-- Table `Ecommerce`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`table1` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`commandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`commandes` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`commandes` (
  `id_commande` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `libelle` VARCHAR(255) NULL,
  `id_client` INT NULL,
  PRIMARY KEY (`id_commande`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`CLIENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`CLIENTS` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`CLIENTS` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `password` CHAR(40) NULL,
  `address1` VARCHAR(255) NULL,
  `address2` VARCHAR(255) NULL,
  `address3` VARCHAR(255) NULL,
  `zip` VARCHAR(5) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(10) NULL,
  `commandes_id_commande` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  INDEX `fk_CLIENTS_commandes_idx` (`commandes_id_commande` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTS_commandes`
    FOREIGN KEY (`commandes_id_commande`)
    REFERENCES `Ecommerce`.`commandes` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`CATEGORIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`CATEGORIES` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`CATEGORIES` (
  `id_categorie` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_categorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`TVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`TVA` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`TVA` (
  `id_tva` INT NOT NULL,
  `libtaux` FLOAT NULL,
  `taux` FLOAT NULL,
  PRIMARY KEY (`id_tva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`ARTICLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`ARTICLES` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`ARTICLES` (
  `id_article` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `prix` FLOAT NOT NULL,
  `poid` FLOAT NOT NULL,
  `description` TEXT NULL,
  `id_categorie` INT NOT NULL,
  `id_tva` INT NOT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `fk_ARTICLES_CATEGORIES1_idx` (`id_categorie` ASC) VISIBLE,
  INDEX `fk_ARTICLES_TVA1_idx` (`id_tva` ASC) VISIBLE,
  CONSTRAINT `fk_ARTICLES_CATEGORIES1`
    FOREIGN KEY (`id_categorie`)
    REFERENCES `Ecommerce`.`CATEGORIES` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTICLES_TVA1`
    FOREIGN KEY (`id_tva`)
    REFERENCES `Ecommerce`.`TVA` (`id_tva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`ARTICLES_has_commandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`ARTICLES_has_commandes` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`ARTICLES_has_commandes` (
  `id_article` INT NOT NULL,
  `id_commande` INT NOT NULL,
  `quantité` INT NULL,
  PRIMARY KEY (`id_article`, `id_commande`),
  INDEX `fk_ARTICLES_has_commandes_commandes1_idx` (`id_commande` ASC) VISIBLE,
  INDEX `fk_ARTICLES_has_commandes_ARTICLES1_idx` (`id_article` ASC) VISIBLE,
  CONSTRAINT `fk_ARTICLES_has_commandes_ARTICLES1`
    FOREIGN KEY (`id_article`)
    REFERENCES `Ecommerce`.`ARTICLES` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTICLES_has_commandes_commandes1`
    FOREIGN KEY (`id_commande`)
    REFERENCES `Ecommerce`.`commandes` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
